### ISSUE TITLE
Problem installing Node Monitor

### ISSUE THREAD

**Issue by RavenHursT** [lorenwest/monitor-dashboard#24]
I tried installing using your npm instructions, both w/ the ```-g``` global flag and without.  I'm getting the following result in both cases.  Am I doing something wrong?

````
$npm install -g monitor-dashboard
npm WARN engine connect@1.7.3: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"node":"0.12.4","npm":"2.10.1"})
\
> ws@0.4.32 install /usr/local/lib/node_modules/monitor-dashboard/node_modules/monitor/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.32 install /usr/local/lib/node_modules/monitor-dashboard/node_modules/monitor/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
monitor-dashboard@0.6.7 /usr/local/lib/node_modules/monitor-dashboard
├── backbone-callbacks@0.1.7 (backbone@0.9.10, underscore@1.4.4)
├── config@0.4.37
├── connect@1.7.3 (mime@1.3.4, qs@4.0.0)
├── core-monitor@0.6.3
└── monitor@0.6.10 (backbone@0.9.9, underscore@1.4.4, cron@0.1.3, socket.io-client@0.9.17, socket.io@0.9.17)
$npm start monitor-dashboard
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start" "monitor-dashboard"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matthewmarcus/WebStormProjects/CaptoraInc/capture-site-validation/npm-debug.log
````

**Comment by lorenwest** [comment]
This may be an issue with a newer version of npm.  Try `npm run start monitor-dashboard`, and if that doesn't work, try changing to the monitor-dashboard directory, and running `node monitor` from there.

**Comment by petergdoyle** [comment]
I too am having problems starting. 
Seems like version incompatibilities somewhere maybe?

```bash
[vagrant@server-perf nodejs]$ npm start monitor-dashboard

> monitor-dashboard@0.6.7 start /vagrant/nodejs/node_modules/monitor-dashboard
> node monitor


/vagrant/nodejs/node_modules/monitor-dashboard/node_modules/connect/node_modules/qs/lib/index.js:5
const Stringify = require('./stringify');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/nodejs/node_modules/monitor-dashboard/node_modules/connect/lib/middleware/bodyParser.js:13:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm ERR! not ok code 0
[vagrant@server-perf nodejs]$ npm run start monitor-dashboard
npm ERR! Error: ENOENT, open '/vagrant/nodejs/node_modules/start/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-229.20.1.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "run" "start" "monitor-dashboard"
npm ERR! cwd /vagrant/nodejs
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! path /vagrant/nodejs/node_modules/start/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/nodejs/npm-debug.log
npm ERR! not ok code 0
```

I get warnings but no errors when I install it
```bash
[vagrant@server-perf nodejs]$ npm install monitor-dashboard --save
npm WARN package.json server-perf-nodejs@0.0.1 No repository field.
npm WARN package.json fs@0.0.2 No repository field.
npm WARN package.json http@0.0.0 No repository field.
npm http GET https://registry.npmjs.org/monitor-dashboard
npm http 304 https://registry.npmjs.org/monitor-dashboard
npm http GET https://registry.npmjs.org/config
npm http GET https://registry.npmjs.org/backbone-callbacks
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/core-monitor
npm http 304 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/config
npm http 304 https://registry.npmjs.org/backbone-callbacks
npm http 304 https://registry.npmjs.org/core-monitor
npm WARN engine connect@1.7.3: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"node":"v0.10.36","npm":"1.3.6"})
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/backbone
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/backbone
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/qs
npm WARN engine qs@6.0.1: wanted: {"node":">=4.0.0"} (current: {"node":"v0.10.36","npm":"1.3.6"})
monitor-dashboard@0.6.7 node_modules/monitor-dashboard
├── backbone-callbacks@0.1.7 (backbone@0.9.10, underscore@1.4.4)
├── config@0.4.37
├── connect@1.7.3 (mime@1.3.4, qs@6.0.1)
└── core-monitor@0.6.3

```

**Comment by petergdoyle** [comment]
running monitor directly yields the same problem...
seems like it is an ECMAScript Harmony specification compatibility problem
not sure I see how/where to find out the requirements to run monitor, monitor-dashboard?

```javascript
[vagrant@server-perf monitor-dashboard]$ node --harmony monitor.js 

             _________                                  __________
___________________  /____      _______ ___________________(_)_  /______________
__  __ \  __ \  __  /_  _ \     __  __ `__ \  __ \_  __ \_  /_  __/  __ \_  ___/
_  / / / /_/ / /_/ / /  __/     _  / / / / / /_/ /  / / /  / / /_ / /_/ /  /
/_/ /_/\____/\__,_/  \___/      /_/ /_/ /_/\____//_/ /_//_/  \__/ \____//_/

Now showing at http://localhost:4200/

External connections disabled.
See /vagrant/nodejs/node_modules/monitor-dashboard/config/external.js for more information.
```
