### ISSUE TITLE
Prototype of undefined

### ISSUE THREAD

**Issue by glennswest** [lorenwest/monitor-dashboard#38]

**Comment by glennswest** [comment]
dhcp-65-33:testdash gwest$ node server.js "monitor" "monitor-js"
Starting

/Users/gwest/testdash/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/gwest/testdash/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gwest/testdash/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:573:32)
dhcp-65-33:testdash gwest$ cd node_modules/monitor-dashboard/
dhcp-65-33:monitor-dashboard gwest$ node monitor.js
/Users/gwest/testdash/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/gwest/testdash/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gwest/testdash/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:573:32)
dhcp-65-33:monitor-dashboard gwest$

**Comment by glennswest** [comment]
Im running on OsX with the latest node and npm. Cannot get past this one.

**Comment by glennswest** [comment]
This appears to be problems in nodejs 7 that is causing this. 
Resolve by switching to use nvm (Node Version Manager and switching to the long term support version)

brew uninstall --force node

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh
| bash

export NVM_DIR="/Users/gwest/.nvm²

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm install v6.9.1

nvm use v6.9.1

nvm alias default 6.9.1

nvm which

**Comment by glennswest** [comment]
can close the issue - Im happy on 6.9.1
