### ISSUE TITLE
Uncaught Exception: mime.lookup is not a function 

### ISSUE THREAD

**Issue by josvaler** [lorenwest/monitor-dashboard#41]
This is what I got

External connections disabled.
See /Users/mtro.josevalerio/programming/NodeJS/dashboard/monitor-dashboard/config/external.js for more information.
Uncaught Exception: mime.lookup is not a function
TypeError: mime.lookup is not a function
    at /Users/mtro.josevalerio/programming/NodeJS/dashboard/monitor-dashboard/node_modules/connect/lib/middleware/static.js:144:17
    at FSReqWrap.oncomplete (fs.js:114:15)

**Comment by fyaowen** [comment]
At line 21
   , mime = require('mime');
=>
   , mime = require('mime-types');

**Comment by hectorsl-sabre** [comment]
Tks
